CREATE TABLE IF NOT EXISTS rol (
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(15) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY (nombre)
);

INSERT IGNORE INTO rol (id,nombre) VALUES
(1,"ROL_ADMIN"),
(2,"ROL_EVALUADOR"),
(3,"ROL_PROPONENTE");
